# Author      : Kenner
# Description : Makefile for CUDA
########################################################

# CUDA
CXX := nvcc

CXXFLAGS := -O3 -std=c++20 -Xcompiler -Wall,-Werror

LINK := $(CXX)

# Link against fmt and thrust 
LDFLAGS := -lfmt

EXEC := DotProductCuda

#############################################################

# Primary build target
all: $(EXEC)

$(EXEC) : DotProductCuda.o
	$(LINK) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

DotProductCuda.o : DotProductCuda.cu
	$(CXX) $(CXXFLAGS) -c $< -o $@

#############################################################

.PHONY : clean
clean :
	@rm -f $(EXEC) a.out core
	@rm -f *.o *.d *~
	@echo "Cleanup complete."